spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mail:
  from: ${MAIL_FROM}
  from-name: ${MAIL_FROM_NAME}

security:
  api-keys:
    - ${USER_MAIL_API_KEY}
    - ${EVENT_MAIL_API_KEY}
    - ${TICKET_MAIL_API_KEY}

logging:
  level:
    root: WARN

server:
  port: ${SERVER_PORT:8082}

rate-limit:
  requests-per-minute: 100
  requests-per-hour: 1000

# Swagger UI config
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
