# Database Configuration
spring:
  datasource:
    url: ${DB_USER_URL:jdbc:postgresql://localhost:5432/Ticket4U-Event}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

# Port
server:
  port: ${SERVER_PORT:8083}

application:
  security:
    # CORS
    cors:
      allowed-origins: ${FRONTEND_URL:https://localhost:3000}

# Logging
logging:
  level:
    root: INFO
#
#  resilience4j.ratelimiter:
#    instances:
#      homePageLimiter: # Đây là tên của instance
#        limitForPeriod: 60              # Số request tối đa
#        limitRefreshPeriod: 1m          # Trong khoảng thời gian bao lâu (1 phút)
#        timeoutDuration: 0s             # Thời gian chờ nếu đã hết lượt (0 là từ chối ngay)