# Database Configuration
spring:
  datasource:
    url: ${DB_USER_URL:jdbc:postgresql://localhost:5432/Ticket4U-Event}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:tintin7335}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        type:
          json_format_mapper: com.ticket4u.config.HibernateJackson3FormatMapper

# Port
server:
  port: ${SERVER_PORT:8083}

# Qdrant Configuration


application:
  application:
    services:
      user-service: http://localhost:8080
  security:
    # CORS
    cors:
      allowed-origins: ${FRONTEND_URL:https://localhost:3000}
    jwt:
      issuer: ${JWT_ISSUER:ticket4u}
      public-key-path: ${JWT_PUBLIC_KEY_PATH:keys/ec-public.pem}
      key-id: ${JWT_KEY_ID:ticket4u-ec-key}

# Logging
logging:
  level:
    root: INFO
#
#  resilience4j.ratelimiter:
#    instances:
#      homePageLimiter: # Đây là tên của instance
#        limitForPeriod: 60              # Số request tối đa
#        limitRefreshPeriod: 1m          # Trong khoảng thời gian bao lâu (1 phút)
#        timeoutDuration: 0s             # Thời gian chờ nếu đã hết lượt (0 là từ chối ngay)