name: ticket4u-app

services:
  user-service:
    image: user-service:latest
    container_name: ticket4u-service-user
    env_file:
      - .env.user-service
      - .env.services
    volumes:
      - ./keys/user-service/ec-private.pem:/keys/ec-private.pem:ro
      - ./keys/user-service/ec-public.pem:/keys/ec-public.pem:ro
    restart: unless-stopped
    networks:
      - ticket4u-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  event-service:
    image: event-service:latest
    container_name: ticket4u-service-event
    env_file:
      - .env.event-service
      - .env.services
    restart: unless-stopped
    networks:
      - ticket4u-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mail-service:
    image: mail-service:latest
    container_name: ticket4u-service-mail
    env_file:
      - .env.mail-service
      - .env.services
    restart: unless-stopped
    networks:
      - ticket4u-network

networks:
  ticket4u-network:
    external: true
