-- CREATE TYPE event_enum AS ENUM (
-- 	'planned',
-- 	'ongoing',
-- 	'finished',
-- 	'cancelled'
-- );

-- CREATE TYPE status_seat_enum AS ENUM (
-- 	'AVAILABLE',
-- 	'BOOKED',
-- 	'HOLD'
-- );
DROP IF EXISTS public.categories;

DROP IF EXISTS public.events;
DROP IF EXISTS public.event_types;
DROP IF EXISTS public.zones;
DROP IF EXISTS public.seats;

DROP IF EXISTS public.venue;
DROP IF EXISTS public.ward;
DROP IF EXISTS public.city;
DROP IF EXISTS public.street_address;

CREATE TABLE IF NOT EXISTS public.categories (
	id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);
COMMENT ON TABLE public.categories IS 'Thể loại của sự kiện';

CREATE TABLE IF NOT EXISTS public.event_types (
	id INTEGER PRIMARY KEY,
	type_name VARCHAR(255),
);

ALTER TABLE IF EXISTS public.event_types
	OWNER to postgres;

insert into public.event_types (id , type_name) values
(0, 'ZONE_BASED'),
(1, 'SEAT_BASED');

CREATE TABLE IF NOT EXISTS public.events (
	id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
	name VARCHAR(255),
	organizer_id UUID, -- references to the table organizers of the users service
	event_type_id INTEGER,
	category_id INTEGER,
	venue_id UUID,
	date DATE,
	start_time TIME,
	end_time TIME,
	status varchar(50) CHECK(status IN ('PLANNED', 'ONGOING', 'FINISHED', 'CANCELLED')),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT event_fk_category FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT event_fk_event_type FOREIGN KEY (event_type_id) REFERENCES public.event_types(id),
    CONSTRAINT event_fk_venue FOREIGN KEY (venue_id) REFERENCES public.venue(id)
);

CREATE TABLE IF NOT EXISTS public.seats (
	id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
	event_id UUID,
	name VARCHAR(255),
	row_name VARCHAR(5),
	col_name VARCHAR(5),
	seat_code VARCHAR(5),
	status varchar(50) CHECK(status IN ('AVAILABLE', 'BOOKED', 'HOLD')),
	price DECIMAL(10,2),
	CONSTRAINT seat_fk_event FOREIGN KEY (event_id) REFERENCES public.events(id)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.zones (
	id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
	event_id UUID,
	name VARCHAR(255),
	capacity INTEGER DEFAULT 0,
	quantity_sold INTEGER DEFAULT 0 CHECK(quantity_sold >= 0),
	price_default DECIMAL(10,2),
	CONSTRAINT zone_fk_event FOREIGN KEY (event_id) REFERENCES public.events(id)
	ON UPDATE NO ACTION ON DELETE NO ACTION
);



CREATE TABLE IF NOT EXISTS public.venue (
	id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
	name_vi VARCHAR(50) NOT NULL,
	name_en VARCHAR(50) NOT NULL,
	address_id INTEGER,
	ward_id INTEGER,
	CONSTRAINT venue_fk_address FOREIGN KEY (address_id) REFERENCES public.street_address(id),
	CONSTRAINT venue_fk_ward FOREIGN KEY (ward_id) REFERENCES public.wards(id),
);

CREATE TABLE IF NOT EXISTS public.street_address (
	id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	name_vi VARCHAR(255) NOT NULL,
	name_en VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS public.wards (
	id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	name_vi VARCHAR(50) NOT NULL,
	name_en VARCHAR(50) NOT NULL,
	city_id INTEGER,
	CONSTRAINT ward_fk_city FOREIGN KEY (city_id) REFERENCES public.cities(id),
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS public.cities (
	id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	name_vi VARCHAR(50) NOT NULL,
	name_en VARCHAR(50) NOT NULL,
	PRIMARY KEY(id)
);
