-- ============================================================
-- EVENT SCHEMA for Ticket4U
-- ============================================================

DROP TABLE IF EXISTS public.seats CASCADE;
DROP TABLE IF EXISTS public.zone_contents CASCADE;
DROP TABLE IF EXISTS public.zones CASCADE;
DROP TABLE IF EXISTS public.event_layout_modifications CASCADE;
DROP TABLE IF EXISTS public.event_layouts CASCADE;
DROP TABLE IF EXISTS public.event_contents CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.venue_layouts CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;


-- ── 1. Categories ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.categories (
    id      INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );


-- ── 2. Venue Layouts ──────────────────────────────────────
-- Reusable templates. Admin creates these.
-- is_public = true  → visible in organizer's selection list (default 10)
-- is_public = false → custom one-off for a specific organizer, hidden from list
CREATE TABLE IF NOT EXISTS public.venue_layouts (
    id          UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    is_public   BOOLEAN NOT NULL DEFAULT TRUE,
    created_by  UUID,                          -- admin UUID who created it
    layout_json JSONB NOT NULL,                -- zones with corners, seats, colors
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );


-- ── 3. Events ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.events (
    id           UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name         VARCHAR(255),
    organizer_id UUID,
    category_id  INTEGER,
    address_line VARCHAR(255),
    start_date   TIMESTAMPTZ,
    end_date     TIMESTAMPTZ,
    status       VARCHAR(50) CHECK (status IN ('PLANNED', 'ONGOING', 'FINISHED', 'CANCELLED')),
    banner_url   TEXT,
    description  TEXT,
    created_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMPTZ,
    CONSTRAINT event_fk_category FOREIGN KEY (category_id)
    REFERENCES public.categories (id) ON UPDATE NO ACTION ON DELETE NO ACTION
    );


-- ── 4. Event Contents ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.event_contents (
    event_id               UUID PRIMARY KEY,
    about_vi               TEXT,
    about_en               TEXT,
    terms_and_conditions   TEXT,
    policy_refund          TEXT,
    seating_plan_image_url TEXT,
    CONSTRAINT content_fk_event FOREIGN KEY (event_id)
    REFERENCES public.events (id) ON DELETE CASCADE
);


-- ── 5. Event Layouts ──────────────────────────────────────
-- Links an event to a venue_layout template, one row per floor/area
CREATE TABLE IF NOT EXISTS public.event_layouts (
    id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL,
    layout_id UUID NOT NULL,
    floor_name VARCHAR(255) NOT NULL DEFAULT 'Main Floor',
    floor_order INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT event_layout_fk_event  FOREIGN KEY (event_id)  REFERENCES public.events (id) ON DELETE CASCADE,
    CONSTRAINT event_layout_fk_layout FOREIGN KEY (layout_id) REFERENCES public.venue_layouts (id) ON DELETE RESTRICT,
    UNIQUE (event_id, floor_order)
    );


-- ── 6. Event Layout Modifications ─────────────────────────
-- Per event+floor overrides: maps template zone names → real zone/seat UUIDs
-- Also allows renaming zones, changing zone types
-- modifications_json structure:
-- {
--   "zones": {
--     "SVIP": {
--       "zone_id": "uuid",
--       "name": { "new": "Khu Vàng" },
--       "type": { "new": "sitting" },
--       "seats": { "A1": "seat-uuid", "A2": "seat-uuid" }
--     },
--     "GA": {
--       "zone_id": "uuid"
--     }
--   }
-- }
CREATE TABLE IF NOT EXISTS public.event_layout_modifications (
    id                UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    event_layout_id   UUID NOT NULL UNIQUE,    -- one modification per event_layout row
    modifications_json JSONB NOT NULL,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mod_fk_event_layout FOREIGN KEY (event_layout_id)
    REFERENCES public.event_layouts (id) ON DELETE CASCADE
    );


-- ── 7. Zones ──────────────────────────────────────────────
-- is_standing = false → seated, individual seats exist in seats table
-- is_standing = true  → standing, no individual seats
CREATE TABLE IF NOT EXISTS public.zones (
                                            id             UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    event_id       UUID,
    name           VARCHAR(255),
    is_standing    BOOLEAN DEFAULT FALSE,
    capacity       INTEGER DEFAULT 0,
    quantity_sold  INTEGER DEFAULT 0 CHECK (quantity_sold >= 0),
    purchase_limit INTEGER NULL,
    price          DECIMAL(10, 2),
    color          VARCHAR(7),                 -- hex e.g. #DC2626
    CONSTRAINT zone_fk_event FOREIGN KEY (event_id)
    REFERENCES public.events (id) ON UPDATE NO ACTION ON DELETE NO ACTION
    );


-- ── 8. Zone Contents ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.zone_contents (
    zone_id        UUID PRIMARY KEY,
    description    TEXT,
    gift_image_url VARCHAR(512),
    perks          JSONB,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT zoneContent_fk_zone FOREIGN KEY (zone_id)
    REFERENCES public.zones (id) ON DELETE CASCADE
    );


-- ── 9. Seats ──────────────────────────────────────────────
-- Only used when zone.is_standing = false
CREATE TABLE IF NOT EXISTS public.seats (
    id             UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    zone_id        UUID,
    name           VARCHAR(255),
    row_name       VARCHAR(5),
    col_name       VARCHAR(5),
    seat_code      VARCHAR(10),
    status         VARCHAR(50) CHECK (status IN ('AVAILABLE', 'BOOKED', 'HOLD')),
    price_override DECIMAL(10, 2),
    CONSTRAINT seat_fk_zone FOREIGN KEY (zone_id)
    REFERENCES public.zones (id) ON UPDATE NO ACTION ON DELETE NO ACTION
    );