
DROP TABLE IF EXISTS public.seats;
DROP TABLE IF EXISTS public.zone_contents;
DROP TABLE IF EXISTS public.zones;
DROP TABLE IF EXISTS public.event_contents;
DROP TABLE IF EXISTS public.events;
DROP TABLE IF EXISTS public.categories;

-- Table: categories

CREATE TABLE IF NOT EXISTS public.categories (
		id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
		name VARCHAR(255) NOT NULL,
		PRIMARY KEY (id)
	);

-- Table: events

CREATE TABLE IF NOT EXISTS public.events (
		id UUID PRIMARY KEY NOT NULL,
		name VARCHAR(255),
		organizer_id UUID,
		category_id INTEGER,
		address_line VARCHAR(255),
		start_date TIMESTAMPTZ,
		end_date TIMESTAMPTZ,
		status varchar(50), -- editing, premier ,selling, paused ,ongoing ,finished ,cancelled
		banner_url TEXT,
		description TEXT,
		created_at TIMESTAMPTZ,
		updated_at TIMESTAMPTZ,
		cancelled_at TIMESTAMPTZ,
		CONSTRAINT event_fk_category FOREIGN KEY (category_id) REFERENCES public.categories (id)
	);

-- Table: event contents
-- This table holds multilingual content and policies for events

CREATE TABLE IF NOT EXISTS public.event_contents (
    event_id UUID PRIMARY KEY, 
    about_vi TEXT,             
    about_en TEXT,             
    terms_and_conditions TEXT,
    policy_refund TEXT,      
	seating_plan_image_url TEXT, -- Hình ảnh sơ đồ chỗ ngồi
    -- faq JSONB,                -- Lưu dạng JSON cho linh hoạt các câu hỏi thường gặp
    CONSTRAINT content_fk_event FOREIGN KEY (event_id) REFERENCES public.events (id) ON DELETE CASCADE --when an event is deleted, its content is also removed
);

-- Table: zones

CREATE TABLE IF NOT EXISTS public.zones (
		id UUID PRIMARY KEY,
		event_id UUID,
		name VARCHAR(255),
		is_standing BOOLEAN,
		capacity INTEGER,
		quantity_sold INTEGER,
		purchase_limit INTEGER, -- null means no limit
		price DECIMAL(10, 2),
		CONSTRAINT zone_fk_event FOREIGN KEY (event_id) REFERENCES public.events (id)
	);

-- Table: zone_contents
-- This table holds multilingual descriptions for zones

CREATE TABLE IF NOT EXISTS public.zone_contents (
    zone_id UUID PRIMARY KEY, -- 1-1 với zone 
    description TEXT, -- Mô tả chi tiết hạng vé
    gift_image_url VARCHAR(512),
    perks JSONB, -- Lưu danh sách ưu đãi dạng [ "Nước uống miễn phí", "Lightstick", "Fansign" ]
    created_at TIMESTAMP,
	updated_at TIMESTAMP,
    CONSTRAINT zoneContent_fk_zone FOREIGN KEY (zone_id) REFERENCES public.zones (id) ON DELETE CASCADE
);

-- Table: seats

CREATE TABLE IF NOT EXISTS public.seats (
		id UUID PRIMARY KEY,
		zone_id UUID,
		name VARCHAR(255),
		row_name VARCHAR(5),
		col_name VARCHAR(5),
		seat_code VARCHAR(5),
		status varchar(50) CHECK (status IN ('AVAILABLE', 'BOOKED', 'HOLD')),
		price_override DECIMAL(10, 2), -- nếu muốn 1 ghế nào đó đặc biệt giá khác trong 1 zone
		CONSTRAINT seat_fk_zone FOREIGN KEY (zone_id) REFERENCES public.zones (id) ON UPDATE NO ACTION ON DELETE NO ACTION
	);